server:
  port: 8080
  contextPath: /SpringBootRestApi
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    data-password: root
    data-username:  root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      show-sql: true
    
    